"""Initial migration

Revision ID: 8cfd5b28f2c9
Revises: 
Create Date: 2025-05-24 15:22:33.069617

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8cfd5b28f2c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_menus')
    op.drop_table('map_objects_3d')
    op.drop_table('flight_paths')
    with op.batch_alter_table('system_users', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_index('username')

    op.drop_table('system_users')
    op.drop_table('user_roles')
    op.drop_table('analysis_results')
    op.drop_table('tasks')
    op.drop_table('plots')
    op.drop_table('role_permissions')
    op.drop_table('system_roles')
    with op.batch_alter_table('system_permissions', schema=None) as batch_op:
        batch_op.drop_index('code')

    op.drop_table('system_permissions')
    with op.batch_alter_table('imagery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata_info', mysql.JSON(), nullable=True, comment='其他元数据信息（传感器、分辨率等）'))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_comment='创建时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_comment='更新时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.drop_column('metadata')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imagery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata', mysql.JSON(), nullable=True, comment='其他元数据信息（传感器、分辨率等）'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_comment='更新时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_comment='创建时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_column('metadata_info')

    op.create_table('system_permissions',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True, comment='权限名称'),
    sa.Column('code', mysql.VARCHAR(length=64), nullable=True, comment='权限编码'),
    sa.Column('description', mysql.TEXT(), nullable=True, comment='权限描述'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('system_permissions', schema=None) as batch_op:
        batch_op.create_index('code', ['code'], unique=True)

    op.create_table('system_roles',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True, comment='角色名称'),
    sa.Column('description', mysql.TEXT(), nullable=True, comment='角色描述'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('role_permissions',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('role_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='角色ID，外键'),
    sa.Column('permission_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='权限ID，外键'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('plots',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True, comment='地块名称'),
    sa.Column('owner_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='用户/组织 ID'),
    sa.Column('geom', mysql.TEXT(), nullable=True, comment='地块边界（Polygon）'),
    sa.Column('area', mysql.FLOAT(), nullable=True, comment='地块面积'),
    sa.Column('soil_type', mysql.VARCHAR(length=128), nullable=True, comment='土壤类型（预留）'),
    sa.Column('crop_type', mysql.VARCHAR(length=128), nullable=True, comment='作物类型（预留）'),
    sa.Column('metadata', mysql.JSON(), nullable=True, comment='其他参数'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tasks',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True, comment='任务名称'),
    sa.Column('description', mysql.TEXT(), nullable=True, comment='任务说明'),
    sa.Column('type', mysql.ENUM('mapping', 'spraying'), nullable=True, comment='任务类型'),
    sa.Column('field_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='外键，指向 plots 表'),
    sa.Column('path_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='外键，指向 flight_paths 表'),
    sa.Column('status', mysql.ENUM('pending', 'running', 'done'), nullable=True, comment='任务状态'),
    sa.Column('volume', mysql.FLOAT(), nullable=True, comment='喷灌量（如有）'),
    sa.Column('schedule_at', mysql.DATETIME(), nullable=True, comment='计划执行时间'),
    sa.Column('metadata', mysql.JSON(), nullable=True, comment='扩展字段，任务参数'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('analysis_results',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True, comment='分析结果名称'),
    sa.Column('description', mysql.TEXT(), nullable=True, comment='分析说明'),
    sa.Column('type', mysql.VARCHAR(length=64), nullable=True, comment='分析类型（NDVI、GNDVI、覆盖率）'),
    sa.Column('result_path', mysql.TEXT(), nullable=True, comment='分析图层存储路径'),
    sa.Column('field_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='所属地块'),
    sa.Column('imagery_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='引用影像'),
    sa.Column('bbox', mysql.TEXT(), nullable=True, comment='分析区域范围'),
    sa.Column('stats', mysql.JSON(), nullable=True, comment='分析统计值，如均值、覆盖率等'),
    sa.Column('style', mysql.JSON(), nullable=True, comment='图层样式（颜色、透明度）'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user_roles',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('user_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='用户ID，外键'),
    sa.Column('role_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='角色ID，外键'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('system_users',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('username', mysql.VARCHAR(length=255), nullable=True, comment='用户名'),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True, comment='邮箱'),
    sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=True, comment='密码哈希'),
    sa.Column('status', mysql.ENUM('active', 'disabled'), server_default=sa.text("'active'"), nullable=True, comment='用户状态'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('system_users', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=True)
        batch_op.create_index('email', ['email'], unique=True)

    op.create_table('flight_paths',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True, comment='航线名称'),
    sa.Column('description', mysql.TEXT(), nullable=True, comment='航线说明'),
    sa.Column('geojson', mysql.JSON(), nullable=True, comment='航线轨迹（GeoJSON 格式）'),
    sa.Column('bbox', mysql.TEXT(), nullable=True, comment='航线范围（MultiLineString）'),
    sa.Column('altitude', mysql.FLOAT(), nullable=True, comment='默认飞行高度'),
    sa.Column('speed', mysql.FLOAT(), nullable=True, comment='默认飞行速度'),
    sa.Column('task_type', mysql.VARCHAR(length=64), nullable=True, comment='任务类型，如测绘/喷洒'),
    sa.Column('metadata', mysql.JSON(), nullable=True, comment='其他参数（飞行间隔、拍照频率等）'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.Column('tags', mysql.JSON(), nullable=True, comment='预留字段，航线分类标签'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('map_objects_3d',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True, comment='显示对象名称'),
    sa.Column('type', mysql.VARCHAR(length=64), nullable=True, comment='对象类型（terrain、imagery、path、task_area）'),
    sa.Column('style', mysql.JSON(), nullable=True, comment='显示样式（颜色、透明度、纹理）'),
    sa.Column('geom', mysql.TEXT(), nullable=True, comment='空间范围（Polygon 或 LineString）'),
    sa.Column('related_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='引用其他对象 ID（如影像、航线）'),
    sa.Column('metadata', mysql.JSON(), nullable=True, comment='其他扩展字段'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('system_menus',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('parent_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='父菜单ID，顶级菜单为 NULL'),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True, comment='菜单名称'),
    sa.Column('path', mysql.VARCHAR(length=255), nullable=True, comment='菜单路径/路由'),
    sa.Column('icon', mysql.VARCHAR(length=64), nullable=True, comment='菜单图标'),
    sa.Column('order_num', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='排序号'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
